/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4e54e7b2-37cc-47ad-925a-74fbe8b3f8c5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mipXmlHKR",
    "aws_user_pools_web_client_id": "lspt4thff9avld17cjr7s7kl1",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://b677gawygzfltmvz5z23aergxm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z76ds76aqjewznednnpevt36ze",
    "aws_user_files_s3_bucket": "ownerdocuments131029-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
